openapi: 3.0.0
servers:
  - url: "http://localhost:1323"
info:
  description: Stamp API
  version: 1.0.0
  title: Stamp API
  contact:
    name: whkelvin
tags:
  - name: post
paths:
  /post:
    post:
      operationId: CreatePost
      tags:
        - post
      summary: create a new post
      description: create a new post
      requestBody:
        description: Create a new post
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostPostRequest"
      responses:
        "201":
          description: post created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "400":
          description: Invalid Input
      security:
        - api_key: []

  /posts:
    get:
      operationId: GetRecentPosts
      tags:
        - post
      summary: get a list of most recent posts
      description: get a list of most recent posts
      parameters:
        - name: size
          in: query
          required: false
          description: Number of results are included in a page
          schema:
            type: integer
            format: int32
            minimum: 0
        - name: lastFetchedItemId
          in: query
          required: false
          description: Guid of the last fetched item, used to retrive next batch of postings. Empty will return the first page.
          schema:
            type: string
      responses:
        "200":
          description: successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostResultSet"
        "400":
          description: Invalid Input

externalDocs:
  description: Find out more about Open API specification
  url: "https://swagger.io/specification/"

components:
  schemas:
    PostPostRequest:
      type: object
      required:
        - title
        - description
        - link
        - rootDomain
      properties:
        title:
          type: string
        description:
          type: string
        link:
          type: string
        rootDomain:
          type: string
    Post:
      type: object
      required:
        - id
        - title
        - description
        - link
        - createdDate
        - rootDomain
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        link:
          type: string
        createdDate:
          type: string
        rootDomain:
          type: string
    PostResultSet:
      type: object
      required:
        - count
        - posts
        - page
        - pageSize
      properties:
        count:
          type: integer
          format: int32
          x-faker:
            datatype.number:
              min: 1
              max: 100
        posts:
          type: array
          items:
            $ref: "#/components/schemas/Post"
        page:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32

  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
